version: '3'
services: # this has two services, one for the web app and one for running tests, both using the same 
#Dockerfile.dev to build the image
  web:
    build: # Build the image using the Dockerfile.dev file in the current directory if mot use build: .
      context: . # directory where the Dockerfile is located
      dockerfile: Dockerfile.dev # ues this since we are in development mode
    ports:
      - "3000:3000"
    volumes:
      - .:/app # Mount the current directory to /app inside the container
      - /app/node_modules # Ignore node_modules to prevent conflicts between host and container
    environment:
      - CHOKIDAR_USEPOLLING=true    
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:  # volumes here are arrays hence we can have multiple volumes, we are mounting the current directory 
    # to /app inside the container and ignoring node_modules to prevent conflicts between host and container
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "test", "--", "--watchAll=false"] # override the default command to run tests 
    #instead of starting the app, --watchAll=false is used to run the tests only once and exit, without it the 
    #tests will keep running and watching for changes.